version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pivot
      MYSQL_USER: pivot
      MYSQL_PASSWORD: pivot
    networks:
      - pivot-network

  app-backend:
    depends_on:
      - db
    image: pivot-backend:latest
    ports:
      - "3000:3000" 
    restart: always
    environment:

    networks:
      - pivot-network

networks:
  pinot-network:
    external: true

volumes:
  db_data: {}
