version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pivot
      MYSQL_USER: pivot
      MYSQL_PASSWORD: pivot
#    networks:
#      - pivot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

  app-backend:
    depends_on:
      - db
    image: pivot-app
    ports:
      - "3000:3000"
    restart: always
##    environment:
#    networks:
#      - pivot-network

#networks:
#  pivot-network:

volumes:
  db_data: {}
